### ISSUE TITLE
Scalariform puts implicit on its own line

### ISSUE THREAD

**Issue by schmmd** [jkinkead/scalariform#5]
I'm trying to make a line shorter.

```
def text[T: StringSerializable: ClassTag](implicit codec: Codec): ArtifactIo[T, FlatArtifact] = new SingletonIo[T]
```

But Scalariform just mangles it.

```
  def text[T: StringSerializable: ClassTag](                                                        
    implicit                                                                                        
    codec: Codec                                                                                    
  ): ArtifactIo[T, FlatArtifact] = new SingletonIo[T]    
```

**Comment by jkinkead** [comment]
Digging into this, the logic behind this formatting is for when you have multiple implicit parameters:
```
def foo(param: String)(
  implicit
  implParam1: TypeA,
  implParam2: TypeB,
  implParam3: TypeC
)
```
Since the `implicit` marks the start of a parameter list, it (arguably) should go on its own line. This reads terribly for a single implicit parameter, though. FWIW, the style guide says [you should put each param list on one line, aligning open parens](http://docs.scala-lang.org/style/declarations.html#methods):
```
def foo(param: String)
       (implicit implParam1: TypeA, implParam2: TypeB, implParam3: TypeC)
```
Of course, there's no examples for how that would look if either parameter list splits onto multiple lines.

At the least, it seems like implicit-on-its-own-line should be an option disabled by default.

**Comment by schmmd** [comment]
I doubt Scalariform does this with `val`/`var` in class parameter lists.  I think it's an oversight.

**Comment by jkinkead** [comment]
It's definitely deliberate: https://github.com/jkinkead/scalariform/blob/a3ddf8199cf5bfb01b328ac92fbbc0caaa0acd16/scalariform/src/main/scala/scalariform/formatter/ExprFormatter.scala#L1210

`val` and `var` apply to a single parameter; `implicit` applies to the whole parameter list.

**Comment by schmmd** [comment]
ahh... I have made peace with Scalariform...

**Comment by jkinkead** [comment]
I dunno, I kind of hate it as-is; it's just terribly, terribly ugly for the single-parameter case - and really, how often do you write multiple implicit parameters?

I'm pushing a change, should be easy to add back in the option to put `implicit` on its own line.
